import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asad's portfolio",
  description: "Generated by Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main>{children}</main>
        <div className="py-10 bg-[#f2cd87]/30 font-semibold">
          <footer>
            <div className="flex flex-wrap gap-12 justify-evenly text-xs bottom-0 ">
              <p>&copy; 2023 Asad Siddiqui. All rights reserved.</p>
              <ul>
                {/* <li>
                <a href="#">Privacy Policy</a>
              </li>
              <li>
                <a href="#">Terms of Service</a>
              </li> */}
                <li className="hover:underline text-black/60 ">
                  <a href="mailto:asads@hey.com?subject=Inquiry&body=Hello Asad, we should connect!">
                    Let's get in touch
                  </a>
                </li>
              </ul>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
