import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio for Asad',
  description: 'Generated by Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className} max-w-3xl mx-auto py-10`}>
        <header>
          <Link href='/'
            className='font-bold text-lg bg-gradient-to-r from-stone-500 via-blue-400 to-orange-500 bg-clip-text text-transparent'
          >
            Asad
          </Link>
        </header>


        <main className='py-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
