import { getPages } from '@/sanity/sanity-utils'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio for Asad',
  description: 'Generated by Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // get all pages

  const pages = await getPages()



  return (
    <html lang="en">

      <body className={`${inter.className} max-w-3xl mx-auto py-10`}>
        <header className='flex items-center justify-between'>
          <Link href='/'
            className='font-bold text-lg bg-gradient-to-r from-stone-500 via-blue-400 to-orange-500 bg-clip-text text-transparent'
          >
            Asad
          </Link>

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link key={page._id}
                href={`/${page.slug}`}
                className='hover:underline'
              >
                {page.title}
              </Link>
            ))}
          </div>

        </header>
        <main className='py-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
